### ISSUE TITLE
LOD issue with Continuity

### ISSUE THREAD

**Issue by Calardaras** [UltimateBoomer/mc-textweaks#13]
I just uploaded it here: https://github.com/helpimnotdrowning/mc-textweaks/releases/tag/1.19-2.0.0

_Originally posted by @helpimnotdrowning in https://github.com/UltimateBoomer/mc-textweaks/issues/12#issuecomment-1175365119_

Continuity brings Connected Textures support to Fabric. I find some compatibility issues with the Continuity mod.
1. Some CTM overlayers won't downscale. 
    According to my test, many resource packs are more or less problematic, and which block it occurs in is not the same.
2. Mipmap and LOD broke totally with the Conquest resource packs.

**Comment by Calardaras** [comment]
![2022-11-20_19 57 32](https://user-images.githubusercontent.com/32061910/202902727-b9226a59-236a-474d-8c42-2fff7ab8a3db.png)
![2022-11-20_19 57 35](https://user-images.githubusercontent.com/32061910/202902731-c7edbf8c-f14e-4ade-8ce8-feab8b72f9e1.png)
grass overlayer works fine in Exalibur.
![2022-11-20_19 52 51](https://user-images.githubusercontent.com/32061910/202902797-26e393c6-42e4-4f45-a250-659978ebb38a.png)
![2022-11-20_19 53 11](https://user-images.githubusercontent.com/32061910/202902805-20da3681-8629-434a-a1db-4728590c1d48.png)
dirt's are broke in Stay True.

**Comment by Calardaras** [comment]
![2022-11-20_20 25 40](https://user-images.githubusercontent.com/32061910/202902927-247e1d83-9825-4774-8eb4-9d3254b2d662.png)
![2022-11-20_20 27 12](https://user-images.githubusercontent.com/32061910/202903122-c366f110-6b13-45b3-92ad-66eed4d5a937.png)
Mipmap and LOD broke totally with the Conquest resource packs.
![2022-11-20_20 33 47](https://user-images.githubusercontent.com/32061910/202903135-2c3e678e-36e2-4984-8041-3736e56fb93a.png)
after I turn off Continiuty

**Comment by helpimnotdrowning** [comment]
All I did to add the 1.18 and 1.19 "compatibility" was change some numbers in the build files (aka i dont really know what I'm doing). Please wait for an official release for newer versions from @UltimateBoomer to raise any issues!

**Comment by Calardaras** [comment]
I just sooooo foolish.
Mipmap caused by 1x1 pixel textures, BUT this mod can naturely upscale textures.
All I have to do is turn up enable upscaling.
Sorry for bothering.

**Comment by Calardaras** [comment]
> All I did to add the 1.18 and 1.19 "compatibility" was change some numbers in the build files (aka i dont really know what I'm doing). Please wait for an official release for newer versions from @UltimateBoomer to raise any issues!

You did a great job, and nothing goes wrong. Thank you sincerely for updating this mod!
