### ISSUE TITLE
Sodium + Indium causes the game to crash when loading a world

### ISSUE THREAD

**Issue by ruvaldak** [UltimateBoomer/mc-textweaks#3]
Title. 

[Indium link](https://github.com/comp500/Indium)

[latest.log](https://github.com/UltimateBoomer/mc-textweaks/files/6237971/latest.log)

**Comment by UltimateBoomer** [comment]
TexTweaks should work just fine with Sodium and Indium. However, I noticed you have Sodium 0.1.0 installed. Currently Indium requires the 1.16.x/next branch of Sodium to work properly, and using the stable build will cause the game to crash on loading the world.

**Comment by ruvaldak** [comment]
> TexTweaks should work just fine with Sodium and Indium. However, I noticed you have Sodium 0.1.0 installed. Currently Indium requires the 1.16.x/next branch of Sodium to work properly, and using the stable build will cause the game to crash on loading the world.

Yup, that was it. My bad, missed that little bit.
